### ISSUE TITLE
Import cannot be resolved

### ISSUE THREAD

**Issue by stefanfreitag** [springframeworkguru/diexample#2]
Hi John,

at present I am watching your course at Udemy.
In one of the source files I noticed an `import` statement that cause some trouble for my IntelliJ.

The statement itself is 
` import com.sun.org.glassfish.external.probe.provider.annotations.ProbeProvider;
`
and the class it is in 
`diexample/src/main/java/guru/springframework/services/HelloWorldServiceEnglishImpl.java
`
(branch "using-profiles")
I removed the unused import and after this I was able to continue.
Could you please review the file?

Thanks,
Stefan

**Comment by springframeworkguru** [comment]
Fixed. Thanks for letting me know. Not sure how that go there. Been there for a long time too.
